### ISSUE TITLE
Conta Spaziature

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/caratteri#1]
A partire dai programmi inviati, crea un programma conta_spaziature.c che conta i caratteri newline, le tabulazioni e i caratteri spazio (3 contatori)

**Comment by luca998** [comment]
Programma creato

**Comment by FabioZTessitore** [comment]
secondo te può succedere che un carattere sia contemporaneamente un newline, uno spazio e una tabulazione?

**Comment by luca998** [comment]
Può darsi
Il 21/Dic/2015 18:16 "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ah può darsi???

**Comment by luca998** [comment]
ho detto una stronzata hahah


2015-12-21 18:35 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
eh. visto che te ne sei accorto allora correggi il codice
