### ISSUE TITLE
Spazi multipli

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/caratteri#3]
Il prossimo programma che devi scrivere è spazi_multipli.c

Così come nei programmi precedenti, il programma deve prendere in input un file e ristamparlo eliminando gli spazi multipli

**Comment by luca998** [comment]
programma caricato

**Comment by FabioZTessitore** [comment]
da chi te lo sei copiato?

**Comment by luca998** [comment]
Hahah da nessuno era abbastanza semplice
Il 21/Dic/2015 20:07 "Fabio Z Tessitore" <notifications@github.com> ha
scritto:
