### ISSUE TITLE
Elimina Commenti

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/caratteri#4]
scrivere un programma che elimina i commenti da un file C

**Comment by luca998** [comment]
Come faccio ad eliminarli?
Il 21/Dic/2015 20:07 "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
non li stampi

**Comment by luca998** [comment]
Ah giusto grazie
Il 21/Dic/2015 20:16 "Luca Caracciolo" <luca.caracciolo16@gmail.com> ha
scritto:

**Comment by luca998** [comment]
ho impiegato un po' di tempo ma l'ho capito alla fine

**Comment by FabioZTessitore** [comment]
ho aggiunto il file test_commenti.c
provalo con

```BASH
$ cc elimina_commenti.c
$ ./a.out < test_commenti.c
```

vedrai che la tua soluzione non funziona

**Comment by FabioZTessitore** [comment]
Il problema che ti ho assegnato non è banale. Bisogna tenere conto di tante cose.

Inoltre cosa succede se devi fare qualche modifica? Per esempio per tenere conto delle stringhe tipo
```C
"/* questo sembra  un commento, ma e' una stringa */"
```
Sei sicuro di poterci mettere le mani per modificarlo?

**Comment by luca998** [comment]
non penso

**Comment by FabioZTessitore** [comment]
Per risolvere facilmente questo tipo di problemi devi imparare a fare un diagramma degli stati.

**Comment by luca998** [comment]
come si fa?

Il giorno 22 dicembre 2015 22:56, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Stato Carattere
-------------------
Input | Output | Prossimo Stato
`c!=' '` | `c` | *Carattere*

**Comment by luca998** [comment]
si, mi è chiaro

**Comment by FabioZTessitore** [comment]
ok, allora bisogna creare un diagramma degli stati per il programma elimina_commenti. Manteniamo lo stato *Carattere* come stato iniziale. Quale carattere di input determina un cambiamento di stato? Quali caratteri no? Prova e vediamo che esce

**Comment by luca998** [comment]
Stato Carattere
Input 	                Output 	       Prossimo Stato
c!=' / ' 	                   c  	                Carattere
c!=' * ' 	                   c 	                Carattere
c==' / ' && c==' * '       NULL             Commento

**Comment by FabioZTessitore** [comment]
per scrivere una tabella devi usare i caratteri | e -
vedi come ho fatto io cliccando sul simbolo della matita del mio post

**Comment by FabioZTessitore** [comment]
la seconda riga è inutile.
la terza è errata perché c non può essere contemporaneamente / e *

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!=' / ` | `c` | *Carattere*
`c==' * `| `c` | *Carattere*

**Comment by FabioZTessitore** [comment]
ancora non ci siamo.

la prima riga va bene, ma se hai deciso che il carattere / è significativo dovresti dire cosa succede se arriva. la seconda riga invece è inutile perché rientra già nella prima (un * è diverso da /)

**Comment by FabioZTessitore** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/' `| NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    ?  |   ? |  ?

**Comment by FabioZTessitore** [comment]
ci sono difficoltà?

**Comment by luca998** [comment]
#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c=='/'  |  c  |  /

**Comment by luca998** [comment]
non sono sicuro che sia così perchè "/" può essere un carattere ma anche un commento

**Comment by FabioZTessitore** [comment]
proprio perché non puoi sapere se è un carattere o l'inizio di un commento non dovresti stamparlo. Quindi niente output. Va bene invece il passaggio di stato.
Ora cosa succede quando siamo nello stato */*?

ps. metti tutte le tabelle nel post così si ha un'idea complessiva (stato carattere e stato / per il momento)

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c=='/'  |  NULL  |  /

**Comment by FabioZTessitore** [comment]
Scusa avevo letto una cosa per un'altra. Quello che ho scritto prima vale nello stato Carattere che avevamo già fatto.
Ora nello stato / di quali input dobbiamo preoccuparci?

**Comment by luca998** [comment]
di '*'?

**Comment by FabioZTessitore** [comment]
Esatto. Se arriva asterisco che succede?
E se arriva un altro carattere?

Il martedì 5 gennaio 2016, luca998 <notifications@github.com> ha scritto:

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  c  |  carattere
    c=='*'  |  NULL  |  *

**Comment by FabioZTessitore** [comment]
c'è un errore e una imperfezione.
Cominciamo dall'imperfezione: quando siamo nello stato / e arriva un * significa che è iniziato un commento. Quindi il prossimo stato potrebbe chiamarsi così.

Invece se arriva un carattere diverso dall'asterisco, siamo d'accordo che deve essere stampato e che si torna allo stato carattere, ma che fine ha fatto il carattere / che non è stato stampato prima?

**Comment by luca998** [comment]
bisogna stampare / quindi?

**Comment by FabioZTessitore** [comment]
anche

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  c  | / e carattere
    c=='*'  |  NULL  |  Commento

**Comment by FabioZTessitore** [comment]
non capisco se hai sbagliato a fare la tabella o se ti sei confuso sul da farsi

**Comment by luca998** [comment]
mi sono confuso prof

**Comment by FabioZTessitore** [comment]
Prima di stampare c bisogna stampare il carattere / che prima abbiamo lasciato in sospeso

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  /, c  |  carattere
    c=='*'  |  NULL  |  Commento

**Comment by luca998** [comment]
così va bene?

**Comment by FabioZTessitore** [comment]
si si

ora aggiungiamo lo stato *commento*.
Quale carattere bisogna tenere d'occhio se siamo in un commento?

**Comment by luca998** [comment]
l'asterisco

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  /, c  |  carattere
    c=='*'  |  NULL  |  Commento

#### Stato *Commento*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  c  |  carattere
    c=='*'  |  NULL  |  Commento
    c!='/'  | * , c  |  carattere
    c=='/'  |  NULL  |  Commento

**Comment by FabioZTessitore** [comment]
Quando sei in stato commento, i carratteri non devono essere stampati. E' questo l'esercizio (eliminare i commenti). Inoltre non è detto che l'asterisco da solo significhi la fine del commento (e' come il caso della / quando sei in stato carattere).

Le ultime due righe sono assolutamente sbagliate. Non puoi fare il test sulla / se già lo hai fatto sull'asterisco. Mi spiego meglio. Se dici che quando c!='*' farai una cerca cosa, rientra anche / tra i caratteri che hai preso in considerazione.

Insomma è tutta da rivedere questa tabella. Cerca di pensare a come proseguire, a come fare tutto lo schema. Non manca molto

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  /, c  |  carattere
    c=='*'  |  NULL  |  Commento

#### Stato *Commento*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  NULL  |  carattere
    c=='*'  |  NULL  |  *

**Comment by FabioZTessitore** [comment]
se siamo in stato commento e becchiamo un carattere diverso da * perché passiamo allo stato carattere?

Manca la tabella relativa allo stato *

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  /, c  |  carattere
    c=='*'  |  NULL  |  Commento

#### Stato *Commento*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  NULL  | Commento
    c=='*'  |  NULL  |  *

#### Stato ***
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='/'  |  NULL  | Commento
    c=='/'  |  NULL  |  /

**Comment by FabioZTessitore** [comment]
ci siamo quasi. manca solo una cosa. che succede se becchi un asterisco quando sei nello stato asterisco? Per come hai fatto le tabelle torni nello stato commento (non funziona una chiusura di commento del tipo **/)

**Comment by luca998** [comment]
#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!='/'` | `c` | *Carattere*
`c=='/'` | NULL | */*

#### Stato */*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  /, c  |  carattere
    c=='*'  |  NULL  |  Commento

#### Stato *Commento*
Input | Output | Prossimo Stato
-------|----------|--------------------
    c!='*'  |  NULL  | Commento
    c=='*'  |  NULL  |  *

#### Stato *
Input | Output | Prossimo Stato
-------|----------|--------------------
   c=='*'  NULL           *
    c!='/'  |  NULL  | Commento
    c=='/'  |  NULL  |  Carattere

**Comment by FabioZTessitore** [comment]
Arriva il codice?

**Comment by luca998** [comment]
Ho caricato il codice

**Comment by FabioZTessitore** [comment]
puoi aggiustare la formattazione del codice?

2016-01-14 19:42 GMT+01:00 luca998 <notifications@github.com>:

**Comment by luca998** [comment]
Come?

**Comment by FabioZTessitore** [comment]
ho aggiustato una parte. continua tu

**Comment by luca998** [comment]
ok
